image: dkudlek/gcc13.2.0-gtest14.4.0

build:debug:
  stage: build
  before_script:
    - export PATH="/usr/local/lib/cmake/GTest:$PATH"
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - cmake --build . --config Debug --target install
  artifacts:
    paths:
      - build

build:release:
  stage: build
  before_script:
    - export PATH="/usr/local/lib/cmake/GTest:$PATH"
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../install
    - cmake --build . --config Release --target install
  artifacts:
    paths:
      - build

test:
  stage: test
  dependencies:
    - "build:release"
    - "build:debug"
  script:
    - cd build
    - ctest -C Release --verbose  --output-junit result_release.xml
    - ctest -C Debug --verbose  --output-junit result_debug.xml
  artifacts:
    when: always
    paths:
      - build/result_release.xml
      - build/result_debug.xml
    reports:
      junit:
        - build/result_release.xml
        - build/result_debug.xml
